spring.config.import=optional:file:.env[.properties]

spring.application.name=Spring Boilerplate

spring.datasource.url=jdbc:postgresql://localhost:5432/my_database
spring.datasource.username=user
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/v1/swagger.html

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.admin.email=${ADMIN_EMAIL}
application.admin.password=${ADMIN_PASSWORD}